### PR TITLE
Karma-Jasmine Documentation

### PR DESCRIPTION
**Pull request by tpatil2**
This Readme file includes complete installation steps for Karma and Jasmine

### CODE REVIEW

**Comment by tpatil2** [comment]
Re-submiting Ref:pull req 301#
resolved merge conflicts...

**Comment by tmjam** [comment]
@tpatil2  Also reference the issue number here

**Comment by tpatil2** [comment]
[issue#300](https://github.com/buildcom/BossyUI/issues/300)

**Comment by radfahrer** [comment]
Remove the graph directive from this pull request.

**Pull request merged**
