### PR TITLE
Finished first pass of toast

### PR DESCRIPTION
**Pull request by erikmellum**
I put an angular.min.js, angular-animate.min.js, style.css, and bossy.toast.html file in the src/directives folder since I wasn't able to get the sandbox to display the widget. I consider it a temporary solution until I figure out / we decide a better standard. I left the timers on the toast for the clarity it offers to a developer seeing it for the first time.

### CODE REVIEW

**Comment by jasonmerino** [comment]
@ErikMellum this needs master merged into it.

**Comment by ErikMellum** [comment]
I want to wait to merge until I see the sandbox jsfiddle correctly open
widgets on my local box. I will try to merge master and test again today.

**Comment by glawson** [comment]
What are we doing with this one?

**Comment by glawson** [comment]
@erikmellum, we'll revisit toast in a few weeks.  At that point I'll need you to update/resolve conflicts.

**Comment by glawson** [comment]
@erikmellum, closing this for now until we revive it.

**Pull request closed without merging**
