### PR TITLE
Modal component Base Barebones

### PR DESCRIPTION
**Pull request by jmwilhite**

### CODE REVIEW

**Comment by glawson** [comment]
@jmwilhite - lint errors:

ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/alert/alert.component.ts[16, 12]: missing whitespace
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/alert/alert.component.ts[17, 9]: missing whitespace
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/alert/alert.component.ts[17, 27]: == should be ===
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/alert/alert.component.ts[17, 38]: missing whitespace
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/alert/alert.component.ts[21, 7]: misplaced 'else'
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/alert/alert.component.ts[21, 14]: missing whitespace
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/alert/alert.component.ts[21, 32]: == should be ===
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/alert/alert.component.ts[21, 43]: missing whitespace
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/alert/alert.component.ts[25, 7]: misplaced 'else'
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/alert/alert.component.ts[25, 11]: missing whitespace
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/alert/alert.component.ts[31, 19]: missing whitespace
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/modal/modal.component.ts[13, 1]: trailing whitespace
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/modal/modal.component.ts[15, 17]: missing whitespace
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/modal/modal.component.ts[20, 1]: trailing whitespace
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/modal/modal.config.ts[2, 34]: expected nospace before colon in parameter
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/modal/modal.config.ts[3, 29]: expected nospace before colon in parameter
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/modal/modal.config.ts[4, 28]: expected nospace before colon in parameter
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/modal/modal.config.ts[5, 31]: expected nospace before colon in parameter
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/modal/modal.config.ts[6, 31]: expected nospace before colon in parameter
ERROR: /home/rof/src/github.com/buildcom/BossyUI/src/bossy-ui/components/modal/modal.config.ts[8, 4]: file should end with a newline

**Comment by glawson** [comment]
@jmwilhite  - you still have some lint issues.

**Comment by jmwilhite** [comment]
I had some issues trying to fix merge conflicts so there are a lot of commits but it is finally up to date

**Comment by glawson** [comment]
@jmwilhite - you now have conflicts :(

**Pull request merged**
