### PR TITLE
Issue #566

### PR DESCRIPTION
**Pull request by Cjoseph4**
We are getting the data correctly but we aren't sure how to hydrate the config. #566

### CODE REVIEW

**Comment by Mriewer** [comment]
Currently the console log is showing that we're grabbing the data correctly, but we're unsure how to hook this data into a config for the form to use.

**Comment by tabersays** [comment]
@Mriewer You should have access to the form after this line https://github.com/buildcom/BossyUI/blob/c148568a3f6678c15dfe99edf353bdcb5eeae5da/src/bossy-ui/components/form/form.ts#L44 If you console.log that out you should see a form object with several elements on it that you should be able to manipulate. Read https://angular.io/api/forms/FormBuilder and https://angular.io/api/forms/FormControl for some information on what is happening.

**Comment by Cjoseph4** [comment]
Thanks Taber, I've been trying to use setValue/patchValue to change the values but It isn't changing the value of the control. Am I on the right track here?
Something like:   this,bossyForm.controls.textInput.patchValue(this.textInput);

**Comment by tabersays** [comment]
You are on the right track using `this.bossyForm.controls.textInput()` Have you console.log'ed what this.textInput is. What is probably tripping you up is that the http.get().subscribe() is happening asyncronously.

**Comment by Cjoseph4** [comment]
You know what, I was totally wrong. It is changing the value it just didn't show it until i clicked on a little tab in the console. We should be just about good to go except getting the api url.

**Comment by Cjoseph4** [comment]
This is basically done but Geoff is meeting with us tomorrow to integrate it with the service nick made for posting.

**Comment by glawson** [comment]
resolves #566

**Pull request merged**
