### PR TITLE
	Initial version of data-grid with type specific column sorting.

### PR DESCRIPTION
**Pull request by radfahrer**
Thoughts, suggestions, critique?

### CODE REVIEW

**Comment by radfahrer** [comment]
Finally updated the data grid directive to get initial data from config rather than being hard coded.

**Comment by jasonmerino** [comment]
@radfahrer looks like this needs master merged into it.

**Comment by radfahrer** [comment]
@jasonmerino (kermit)

**Comment by jasonmerino** [comment]
@radfahrer sorry, I think I broke (kermit). Re-merge master?

**Comment by radfahrer** [comment]
(kermit) again

**Pull request merged**
